// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmi.proto

package cmi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Status contains the possible status for machines running on the cloud
type GetMachineResponse_Status int32

const (
	GetMachineResponse_Unknown GetMachineResponse_Status = 0
	GetMachineResponse_Running GetMachineResponse_Status = 1
	GetMachineResponse_Stopped GetMachineResponse_Status = 2
)

var GetMachineResponse_Status_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Stopped",
}
var GetMachineResponse_Status_value = map[string]int32{
	"Unknown": 0,
	"Running": 1,
	"Stopped": 2,
}

func (x GetMachineResponse_Status) String() string {
	return proto.EnumName(GetMachineResponse_Status_name, int32(x))
}
func (GetMachineResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{5, 0}
}

type PluginCapability_Service_Type int32

const (
	PluginCapability_Service_UNKNOWN            PluginCapability_Service_Type = 0
	PluginCapability_Service_CONTROLLER_SERVICE PluginCapability_Service_Type = 1
)

var PluginCapability_Service_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONTROLLER_SERVICE",
}
var PluginCapability_Service_Type_value = map[string]int32{
	"UNKNOWN":            0,
	"CONTROLLER_SERVICE": 1,
}

func (x PluginCapability_Service_Type) String() string {
	return proto.EnumName(PluginCapability_Service_Type_name, int32(x))
}
func (PluginCapability_Service_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{18, 0, 0}
}

type CreateMachineRequest struct {
	// Name is the name of the machine to be created by driver.
	// This field is REQUIRED.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// ProviderSpec is the configuration needed to create a machine in bytes.
	// Driver should parse this raw data into pre-defined spec in their respective projects.
	// This field is REQUIRED.
	ProviderSpec []byte `protobuf:"bytes,2,opt,name=ProviderSpec,proto3" json:"ProviderSpec,omitempty"`
	// Secrets is the map containing necessary credentials for cloud-provider to create the machine.
	// This field is OPTIONAL.
	Secrets              map[string][]byte `protobuf:"bytes,3,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateMachineRequest) Reset()         { *m = CreateMachineRequest{} }
func (m *CreateMachineRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMachineRequest) ProtoMessage()    {}
func (*CreateMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{0}
}
func (m *CreateMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineRequest.Unmarshal(m, b)
}
func (m *CreateMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineRequest.Marshal(b, m, deterministic)
}
func (dst *CreateMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineRequest.Merge(dst, src)
}
func (m *CreateMachineRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMachineRequest.Size(m)
}
func (m *CreateMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineRequest proto.InternalMessageInfo

func (m *CreateMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMachineRequest) GetProviderSpec() []byte {
	if m != nil {
		return m.ProviderSpec
	}
	return nil
}

func (m *CreateMachineRequest) GetSecrets() map[string][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type CreateMachineResponse struct {
	// MachineID is the unique identification of the VM at the cloud provider.
	// This could be the same/different from req.Name.
	// MachineID typically matches with the node.Spec.ProviderID on the node object.
	// Eg: gce://project-name/region/vm-machineID
	// This field is REQUIRED.
	MachineID string `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	// NodeName is the name of the node-object registered to kubernetes.
	// This field is REQUIRED.
	NodeName             string   `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMachineResponse) Reset()         { *m = CreateMachineResponse{} }
func (m *CreateMachineResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMachineResponse) ProtoMessage()    {}
func (*CreateMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{1}
}
func (m *CreateMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMachineResponse.Unmarshal(m, b)
}
func (m *CreateMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMachineResponse.Marshal(b, m, deterministic)
}
func (dst *CreateMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMachineResponse.Merge(dst, src)
}
func (m *CreateMachineResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMachineResponse.Size(m)
}
func (m *CreateMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMachineResponse proto.InternalMessageInfo

func (m *CreateMachineResponse) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *CreateMachineResponse) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

type DeleteMachineRequest struct {
	// MachineID is the id of the machine to be deleted.
	// It should uniquely identify the real machine in cloud-provider.
	// This field is REQUIRED.
	MachineID string `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	// Secrets is the map containing necessary credentials for cloud-provider to delete the machine.
	// This field is OPTIONAL.
	Secrets              map[string][]byte `protobuf:"bytes,2,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteMachineRequest) Reset()         { *m = DeleteMachineRequest{} }
func (m *DeleteMachineRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMachineRequest) ProtoMessage()    {}
func (*DeleteMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{2}
}
func (m *DeleteMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMachineRequest.Unmarshal(m, b)
}
func (m *DeleteMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMachineRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMachineRequest.Merge(dst, src)
}
func (m *DeleteMachineRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMachineRequest.Size(m)
}
func (m *DeleteMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMachineRequest proto.InternalMessageInfo

func (m *DeleteMachineRequest) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *DeleteMachineRequest) GetSecrets() map[string][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type DeleteMachineResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMachineResponse) Reset()         { *m = DeleteMachineResponse{} }
func (m *DeleteMachineResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMachineResponse) ProtoMessage()    {}
func (*DeleteMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{3}
}
func (m *DeleteMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMachineResponse.Unmarshal(m, b)
}
func (m *DeleteMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMachineResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMachineResponse.Merge(dst, src)
}
func (m *DeleteMachineResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMachineResponse.Size(m)
}
func (m *DeleteMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMachineResponse proto.InternalMessageInfo

type GetMachineRequest struct {
	// MachineID is the id of the machine whose status is to be determined.
	// It should uniquely identify the real machine in cloud-provider.
	// This field is REQUIRED.
	MachineID string `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	// Secrets is the map containing necessary credentials for cloud-provider to list the machines.
	// This field is OPTIONAL.
	Secrets              map[string][]byte `protobuf:"bytes,2,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMachineRequest) Reset()         { *m = GetMachineRequest{} }
func (m *GetMachineRequest) String() string { return proto.CompactTextString(m) }
func (*GetMachineRequest) ProtoMessage()    {}
func (*GetMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{4}
}
func (m *GetMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMachineRequest.Unmarshal(m, b)
}
func (m *GetMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMachineRequest.Marshal(b, m, deterministic)
}
func (dst *GetMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMachineRequest.Merge(dst, src)
}
func (m *GetMachineRequest) XXX_Size() int {
	return xxx_messageInfo_GetMachineRequest.Size(m)
}
func (m *GetMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMachineRequest proto.InternalMessageInfo

func (m *GetMachineRequest) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *GetMachineRequest) GetSecrets() map[string][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type GetMachineResponse struct {
	// Exists tells if the machine exists on the cloud provider
	// This field is REQUIRED.
	Exists               bool                      `protobuf:"varint,1,opt,name=Exists,proto3" json:"Exists,omitempty"`
	MachineStatus        GetMachineResponse_Status `protobuf:"varint,2,opt,name=MachineStatus,proto3,enum=cmi.v1.GetMachineResponse_Status" json:"MachineStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetMachineResponse) Reset()         { *m = GetMachineResponse{} }
func (m *GetMachineResponse) String() string { return proto.CompactTextString(m) }
func (*GetMachineResponse) ProtoMessage()    {}
func (*GetMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{5}
}
func (m *GetMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMachineResponse.Unmarshal(m, b)
}
func (m *GetMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMachineResponse.Marshal(b, m, deterministic)
}
func (dst *GetMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMachineResponse.Merge(dst, src)
}
func (m *GetMachineResponse) XXX_Size() int {
	return xxx_messageInfo_GetMachineResponse.Size(m)
}
func (m *GetMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMachineResponse proto.InternalMessageInfo

func (m *GetMachineResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetMachineResponse) GetMachineStatus() GetMachineResponse_Status {
	if m != nil {
		return m.MachineStatus
	}
	return GetMachineResponse_Unknown
}

type ListMachinesRequest struct {
	// ProviderSpec is the configuration needed to list machines.
	// Driver should parse this raw data into pre-defined spec in their respective projects.
	// This field is REQUIRED.
	ProviderSpec []byte `protobuf:"bytes,1,opt,name=ProviderSpec,proto3" json:"ProviderSpec,omitempty"`
	// Secrets is the map containing necessary credentials for cloud-provider to list the machines.
	// This field is OPTIONAL.
	Secrets              map[string][]byte `protobuf:"bytes,2,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListMachinesRequest) Reset()         { *m = ListMachinesRequest{} }
func (m *ListMachinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMachinesRequest) ProtoMessage()    {}
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{6}
}
func (m *ListMachinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMachinesRequest.Unmarshal(m, b)
}
func (m *ListMachinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMachinesRequest.Marshal(b, m, deterministic)
}
func (dst *ListMachinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMachinesRequest.Merge(dst, src)
}
func (m *ListMachinesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMachinesRequest.Size(m)
}
func (m *ListMachinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMachinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMachinesRequest proto.InternalMessageInfo

func (m *ListMachinesRequest) GetProviderSpec() []byte {
	if m != nil {
		return m.ProviderSpec
	}
	return nil
}

func (m *ListMachinesRequest) GetSecrets() map[string][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ListMachinesResponse struct {
	// MachineList is the map of list of machines. Format for the map should be map<MachineID, MachineName>.
	// This field is REQUIRED.
	MachineList          map[string]string `protobuf:"bytes,1,rep,name=MachineList,proto3" json:"MachineList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListMachinesResponse) Reset()         { *m = ListMachinesResponse{} }
func (m *ListMachinesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMachinesResponse) ProtoMessage()    {}
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{7}
}
func (m *ListMachinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMachinesResponse.Unmarshal(m, b)
}
func (m *ListMachinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMachinesResponse.Marshal(b, m, deterministic)
}
func (dst *ListMachinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMachinesResponse.Merge(dst, src)
}
func (m *ListMachinesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMachinesResponse.Size(m)
}
func (m *ListMachinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMachinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMachinesResponse proto.InternalMessageInfo

func (m *ListMachinesResponse) GetMachineList() map[string]string {
	if m != nil {
		return m.MachineList
	}
	return nil
}

type ShutDownMachineRequest struct {
	// MachineID is the id of the machine to be shut-down.
	// It should uniquely identify the real machine in cloud-provider.
	// This field is REQUIRED.
	MachineID string `protobuf:"bytes,1,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	// Secrets is the map containing necessary credentials for cloud-provider to delete the machine.
	// This field is OPTIONAL.
	Secrets              map[string][]byte `protobuf:"bytes,2,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShutDownMachineRequest) Reset()         { *m = ShutDownMachineRequest{} }
func (m *ShutDownMachineRequest) String() string { return proto.CompactTextString(m) }
func (*ShutDownMachineRequest) ProtoMessage()    {}
func (*ShutDownMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{8}
}
func (m *ShutDownMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutDownMachineRequest.Unmarshal(m, b)
}
func (m *ShutDownMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutDownMachineRequest.Marshal(b, m, deterministic)
}
func (dst *ShutDownMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutDownMachineRequest.Merge(dst, src)
}
func (m *ShutDownMachineRequest) XXX_Size() int {
	return xxx_messageInfo_ShutDownMachineRequest.Size(m)
}
func (m *ShutDownMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutDownMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutDownMachineRequest proto.InternalMessageInfo

func (m *ShutDownMachineRequest) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *ShutDownMachineRequest) GetSecrets() map[string][]byte {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ShutDownMachineResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutDownMachineResponse) Reset()         { *m = ShutDownMachineResponse{} }
func (m *ShutDownMachineResponse) String() string { return proto.CompactTextString(m) }
func (*ShutDownMachineResponse) ProtoMessage()    {}
func (*ShutDownMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{9}
}
func (m *ShutDownMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutDownMachineResponse.Unmarshal(m, b)
}
func (m *ShutDownMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutDownMachineResponse.Marshal(b, m, deterministic)
}
func (dst *ShutDownMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutDownMachineResponse.Merge(dst, src)
}
func (m *ShutDownMachineResponse) XXX_Size() int {
	return xxx_messageInfo_ShutDownMachineResponse.Size(m)
}
func (m *ShutDownMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutDownMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutDownMachineResponse proto.InternalMessageInfo

type GetListOfVolumeIDsForExistingPVsRequest struct {
	// PVSpecsList is a list PV specs for whom volume-IDs are required
	// Driver should parse this raw data into pre-defined list of PVSpecs
	// This field is REQUIRED.
	PVSpecList           []byte   `protobuf:"bytes,1,opt,name=PVSpecList,proto3" json:"PVSpecList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListOfVolumeIDsForExistingPVsRequest) Reset() {
	*m = GetListOfVolumeIDsForExistingPVsRequest{}
}
func (m *GetListOfVolumeIDsForExistingPVsRequest) String() string { return proto.CompactTextString(m) }
func (*GetListOfVolumeIDsForExistingPVsRequest) ProtoMessage()    {}
func (*GetListOfVolumeIDsForExistingPVsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{10}
}
func (m *GetListOfVolumeIDsForExistingPVsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest.Unmarshal(m, b)
}
func (m *GetListOfVolumeIDsForExistingPVsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest.Marshal(b, m, deterministic)
}
func (dst *GetListOfVolumeIDsForExistingPVsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest.Merge(dst, src)
}
func (m *GetListOfVolumeIDsForExistingPVsRequest) XXX_Size() int {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest.Size(m)
}
func (m *GetListOfVolumeIDsForExistingPVsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListOfVolumeIDsForExistingPVsRequest proto.InternalMessageInfo

func (m *GetListOfVolumeIDsForExistingPVsRequest) GetPVSpecList() []byte {
	if m != nil {
		return m.PVSpecList
	}
	return nil
}

type GetListOfVolumeIDsForExistingPVsResponse struct {
	// VolumeIDList is a list of VolumeIDs. Format for the map should be map<MachineID, MachineName>.
	// This field is REQUIRED.
	VolumeIDList         string   `protobuf:"bytes,1,opt,name=VolumeIDList,proto3" json:"VolumeIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListOfVolumeIDsForExistingPVsResponse) Reset() {
	*m = GetListOfVolumeIDsForExistingPVsResponse{}
}
func (m *GetListOfVolumeIDsForExistingPVsResponse) String() string { return proto.CompactTextString(m) }
func (*GetListOfVolumeIDsForExistingPVsResponse) ProtoMessage()    {}
func (*GetListOfVolumeIDsForExistingPVsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{11}
}
func (m *GetListOfVolumeIDsForExistingPVsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse.Unmarshal(m, b)
}
func (m *GetListOfVolumeIDsForExistingPVsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse.Marshal(b, m, deterministic)
}
func (dst *GetListOfVolumeIDsForExistingPVsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse.Merge(dst, src)
}
func (m *GetListOfVolumeIDsForExistingPVsResponse) XXX_Size() int {
	return xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse.Size(m)
}
func (m *GetListOfVolumeIDsForExistingPVsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListOfVolumeIDsForExistingPVsResponse proto.InternalMessageInfo

func (m *GetListOfVolumeIDsForExistingPVsResponse) GetVolumeIDList() string {
	if m != nil {
		return m.VolumeIDList
	}
	return ""
}

// TODO[hardikdr]: Make use of this field.
type ControllerGetCapabilitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerGetCapabilitiesRequest) Reset()         { *m = ControllerGetCapabilitiesRequest{} }
func (m *ControllerGetCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ControllerGetCapabilitiesRequest) ProtoMessage()    {}
func (*ControllerGetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{12}
}
func (m *ControllerGetCapabilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerGetCapabilitiesRequest.Unmarshal(m, b)
}
func (m *ControllerGetCapabilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerGetCapabilitiesRequest.Marshal(b, m, deterministic)
}
func (dst *ControllerGetCapabilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerGetCapabilitiesRequest.Merge(dst, src)
}
func (m *ControllerGetCapabilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ControllerGetCapabilitiesRequest.Size(m)
}
func (m *ControllerGetCapabilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerGetCapabilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerGetCapabilitiesRequest proto.InternalMessageInfo

// TODO[hardikdr]: Make use of this field.
type ControllerGetCapabilitiesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerGetCapabilitiesResponse) Reset()         { *m = ControllerGetCapabilitiesResponse{} }
func (m *ControllerGetCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ControllerGetCapabilitiesResponse) ProtoMessage()    {}
func (*ControllerGetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{13}
}
func (m *ControllerGetCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerGetCapabilitiesResponse.Unmarshal(m, b)
}
func (m *ControllerGetCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerGetCapabilitiesResponse.Marshal(b, m, deterministic)
}
func (dst *ControllerGetCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerGetCapabilitiesResponse.Merge(dst, src)
}
func (m *ControllerGetCapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ControllerGetCapabilitiesResponse.Size(m)
}
func (m *ControllerGetCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerGetCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerGetCapabilitiesResponse proto.InternalMessageInfo

type GetPluginInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginInfoRequest) Reset()         { *m = GetPluginInfoRequest{} }
func (m *GetPluginInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoRequest) ProtoMessage()    {}
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{14}
}
func (m *GetPluginInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoRequest.Unmarshal(m, b)
}
func (m *GetPluginInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetPluginInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoRequest.Merge(dst, src)
}
func (m *GetPluginInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoRequest.Size(m)
}
func (m *GetPluginInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoRequest proto.InternalMessageInfo

type GetPluginInfoResponse struct {
	// The name MUST follow domain name notation format
	// (https://tools.ietf.org/html/rfc1035#section-2.3.1). It SHOULD
	// include the plugin's host company name and the plugin name,
	// to minimize the possibility of collisions. It MUST be 63
	// characters or less, beginning and ending with an alphanumeric
	// character ([a-z0-9A-Z]) with dashes (-), dots (.), and
	// alphanumerics between. This field is REQUIRED.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This field is REQUIRED. Value of this field is opaque to the CO.
	VendorVersion string `protobuf:"bytes,2,opt,name=vendor_version,json=vendorVersion,proto3" json:"vendor_version,omitempty"`
	// This field is OPTIONAL. Values are opaque to the CO.
	Manifest             map[string]string `protobuf:"bytes,3,rep,name=manifest,proto3" json:"manifest,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPluginInfoResponse) Reset()         { *m = GetPluginInfoResponse{} }
func (m *GetPluginInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetPluginInfoResponse) ProtoMessage()    {}
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{15}
}
func (m *GetPluginInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginInfoResponse.Unmarshal(m, b)
}
func (m *GetPluginInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetPluginInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginInfoResponse.Merge(dst, src)
}
func (m *GetPluginInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetPluginInfoResponse.Size(m)
}
func (m *GetPluginInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginInfoResponse proto.InternalMessageInfo

func (m *GetPluginInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPluginInfoResponse) GetVendorVersion() string {
	if m != nil {
		return m.VendorVersion
	}
	return ""
}

func (m *GetPluginInfoResponse) GetManifest() map[string]string {
	if m != nil {
		return m.Manifest
	}
	return nil
}

type GetPluginCapabilitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginCapabilitiesRequest) Reset()         { *m = GetPluginCapabilitiesRequest{} }
func (m *GetPluginCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPluginCapabilitiesRequest) ProtoMessage()    {}
func (*GetPluginCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{16}
}
func (m *GetPluginCapabilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginCapabilitiesRequest.Unmarshal(m, b)
}
func (m *GetPluginCapabilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginCapabilitiesRequest.Marshal(b, m, deterministic)
}
func (dst *GetPluginCapabilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginCapabilitiesRequest.Merge(dst, src)
}
func (m *GetPluginCapabilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPluginCapabilitiesRequest.Size(m)
}
func (m *GetPluginCapabilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginCapabilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginCapabilitiesRequest proto.InternalMessageInfo

type GetPluginCapabilitiesResponse struct {
	// All the capabilities that the controller service supports. This
	// field is OPTIONAL.
	Capabilities         []*PluginCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPluginCapabilitiesResponse) Reset()         { *m = GetPluginCapabilitiesResponse{} }
func (m *GetPluginCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPluginCapabilitiesResponse) ProtoMessage()    {}
func (*GetPluginCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{17}
}
func (m *GetPluginCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginCapabilitiesResponse.Unmarshal(m, b)
}
func (m *GetPluginCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginCapabilitiesResponse.Marshal(b, m, deterministic)
}
func (dst *GetPluginCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginCapabilitiesResponse.Merge(dst, src)
}
func (m *GetPluginCapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPluginCapabilitiesResponse.Size(m)
}
func (m *GetPluginCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginCapabilitiesResponse proto.InternalMessageInfo

func (m *GetPluginCapabilitiesResponse) GetCapabilities() []*PluginCapability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// Specifies a capability of the plugin.
type PluginCapability struct {
	// Types that are valid to be assigned to Type:
	//	*PluginCapability_Service_
	Type                 isPluginCapability_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PluginCapability) Reset()         { *m = PluginCapability{} }
func (m *PluginCapability) String() string { return proto.CompactTextString(m) }
func (*PluginCapability) ProtoMessage()    {}
func (*PluginCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{18}
}
func (m *PluginCapability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginCapability.Unmarshal(m, b)
}
func (m *PluginCapability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginCapability.Marshal(b, m, deterministic)
}
func (dst *PluginCapability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginCapability.Merge(dst, src)
}
func (m *PluginCapability) XXX_Size() int {
	return xxx_messageInfo_PluginCapability.Size(m)
}
func (m *PluginCapability) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginCapability.DiscardUnknown(m)
}

var xxx_messageInfo_PluginCapability proto.InternalMessageInfo

type isPluginCapability_Type interface {
	isPluginCapability_Type()
}

type PluginCapability_Service_ struct {
	Service *PluginCapability_Service `protobuf:"bytes,1,opt,name=service,proto3,oneof"`
}

func (*PluginCapability_Service_) isPluginCapability_Type() {}

func (m *PluginCapability) GetType() isPluginCapability_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *PluginCapability) GetService() *PluginCapability_Service {
	if x, ok := m.GetType().(*PluginCapability_Service_); ok {
		return x.Service
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PluginCapability) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PluginCapability_OneofMarshaler, _PluginCapability_OneofUnmarshaler, _PluginCapability_OneofSizer, []interface{}{
		(*PluginCapability_Service_)(nil),
	}
}

func _PluginCapability_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PluginCapability)
	// type
	switch x := m.Type.(type) {
	case *PluginCapability_Service_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Service); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PluginCapability.Type has unexpected type %T", x)
	}
	return nil
}

func _PluginCapability_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PluginCapability)
	switch tag {
	case 1: // type.service
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PluginCapability_Service)
		err := b.DecodeMessage(msg)
		m.Type = &PluginCapability_Service_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PluginCapability_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PluginCapability)
	// type
	switch x := m.Type.(type) {
	case *PluginCapability_Service_:
		s := proto.Size(x.Service)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PluginCapability_Service struct {
	Type                 PluginCapability_Service_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cmi.v1.PluginCapability_Service_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PluginCapability_Service) Reset()         { *m = PluginCapability_Service{} }
func (m *PluginCapability_Service) String() string { return proto.CompactTextString(m) }
func (*PluginCapability_Service) ProtoMessage()    {}
func (*PluginCapability_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{18, 0}
}
func (m *PluginCapability_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginCapability_Service.Unmarshal(m, b)
}
func (m *PluginCapability_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginCapability_Service.Marshal(b, m, deterministic)
}
func (dst *PluginCapability_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginCapability_Service.Merge(dst, src)
}
func (m *PluginCapability_Service) XXX_Size() int {
	return xxx_messageInfo_PluginCapability_Service.Size(m)
}
func (m *PluginCapability_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginCapability_Service.DiscardUnknown(m)
}

var xxx_messageInfo_PluginCapability_Service proto.InternalMessageInfo

func (m *PluginCapability_Service) GetType() PluginCapability_Service_Type {
	if m != nil {
		return m.Type
	}
	return PluginCapability_Service_UNKNOWN
}

type ProbeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeRequest) Reset()         { *m = ProbeRequest{} }
func (m *ProbeRequest) String() string { return proto.CompactTextString(m) }
func (*ProbeRequest) ProtoMessage()    {}
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{19}
}
func (m *ProbeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeRequest.Unmarshal(m, b)
}
func (m *ProbeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeRequest.Marshal(b, m, deterministic)
}
func (dst *ProbeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeRequest.Merge(dst, src)
}
func (m *ProbeRequest) XXX_Size() int {
	return xxx_messageInfo_ProbeRequest.Size(m)
}
func (m *ProbeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeRequest proto.InternalMessageInfo

type ProbeResponse struct {
	Ready                *wrappers.BoolValue `protobuf:"bytes,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProbeResponse) Reset()         { *m = ProbeResponse{} }
func (m *ProbeResponse) String() string { return proto.CompactTextString(m) }
func (*ProbeResponse) ProtoMessage()    {}
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmi_f0b5fd4205dba277, []int{20}
}
func (m *ProbeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeResponse.Unmarshal(m, b)
}
func (m *ProbeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeResponse.Marshal(b, m, deterministic)
}
func (dst *ProbeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeResponse.Merge(dst, src)
}
func (m *ProbeResponse) XXX_Size() int {
	return xxx_messageInfo_ProbeResponse.Size(m)
}
func (m *ProbeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeResponse proto.InternalMessageInfo

func (m *ProbeResponse) GetReady() *wrappers.BoolValue {
	if m != nil {
		return m.Ready
	}
	return nil
}

var E_CmiSecret = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1059,
	Name:          "cmi.v1.cmi_secret",
	Tag:           "varint,1059,opt,name=cmi_secret,json=cmiSecret",
	Filename:      "cmi.proto",
}

func init() {
	proto.RegisterType((*CreateMachineRequest)(nil), "cmi.v1.CreateMachineRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "cmi.v1.CreateMachineRequest.SecretsEntry")
	proto.RegisterType((*CreateMachineResponse)(nil), "cmi.v1.CreateMachineResponse")
	proto.RegisterType((*DeleteMachineRequest)(nil), "cmi.v1.DeleteMachineRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "cmi.v1.DeleteMachineRequest.SecretsEntry")
	proto.RegisterType((*DeleteMachineResponse)(nil), "cmi.v1.DeleteMachineResponse")
	proto.RegisterType((*GetMachineRequest)(nil), "cmi.v1.GetMachineRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "cmi.v1.GetMachineRequest.SecretsEntry")
	proto.RegisterType((*GetMachineResponse)(nil), "cmi.v1.GetMachineResponse")
	proto.RegisterType((*ListMachinesRequest)(nil), "cmi.v1.ListMachinesRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "cmi.v1.ListMachinesRequest.SecretsEntry")
	proto.RegisterType((*ListMachinesResponse)(nil), "cmi.v1.ListMachinesResponse")
	proto.RegisterMapType((map[string]string)(nil), "cmi.v1.ListMachinesResponse.MachineListEntry")
	proto.RegisterType((*ShutDownMachineRequest)(nil), "cmi.v1.ShutDownMachineRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "cmi.v1.ShutDownMachineRequest.SecretsEntry")
	proto.RegisterType((*ShutDownMachineResponse)(nil), "cmi.v1.ShutDownMachineResponse")
	proto.RegisterType((*GetListOfVolumeIDsForExistingPVsRequest)(nil), "cmi.v1.GetListOfVolumeIDsForExistingPVsRequest")
	proto.RegisterType((*GetListOfVolumeIDsForExistingPVsResponse)(nil), "cmi.v1.GetListOfVolumeIDsForExistingPVsResponse")
	proto.RegisterType((*ControllerGetCapabilitiesRequest)(nil), "cmi.v1.ControllerGetCapabilitiesRequest")
	proto.RegisterType((*ControllerGetCapabilitiesResponse)(nil), "cmi.v1.ControllerGetCapabilitiesResponse")
	proto.RegisterType((*GetPluginInfoRequest)(nil), "cmi.v1.GetPluginInfoRequest")
	proto.RegisterType((*GetPluginInfoResponse)(nil), "cmi.v1.GetPluginInfoResponse")
	proto.RegisterMapType((map[string]string)(nil), "cmi.v1.GetPluginInfoResponse.ManifestEntry")
	proto.RegisterType((*GetPluginCapabilitiesRequest)(nil), "cmi.v1.GetPluginCapabilitiesRequest")
	proto.RegisterType((*GetPluginCapabilitiesResponse)(nil), "cmi.v1.GetPluginCapabilitiesResponse")
	proto.RegisterType((*PluginCapability)(nil), "cmi.v1.PluginCapability")
	proto.RegisterType((*PluginCapability_Service)(nil), "cmi.v1.PluginCapability.Service")
	proto.RegisterType((*ProbeRequest)(nil), "cmi.v1.ProbeRequest")
	proto.RegisterType((*ProbeResponse)(nil), "cmi.v1.ProbeResponse")
	proto.RegisterEnum("cmi.v1.GetMachineResponse_Status", GetMachineResponse_Status_name, GetMachineResponse_Status_value)
	proto.RegisterEnum("cmi.v1.PluginCapability_Service_Type", PluginCapability_Service_Type_name, PluginCapability_Service_Type_value)
	proto.RegisterExtension(E_CmiSecret)
}

func init() { proto.RegisterFile("cmi.proto", fileDescriptor_cmi_f0b5fd4205dba277) }

var fileDescriptor_cmi_f0b5fd4205dba277 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x6f, 0xe3, 0xc4,
	0x1b, 0xcf, 0xf4, 0xbd, 0x4f, 0x93, 0xfe, 0xf3, 0x1f, 0xd2, 0x6e, 0x6a, 0xda, 0x92, 0x35, 0x14,
	0xb2, 0xaa, 0x70, 0x97, 0x20, 0x21, 0x28, 0x0b, 0x12, 0x49, 0xb3, 0xd9, 0xb0, 0xdd, 0xa4, 0x38,
	0x25, 0x48, 0x48, 0xa8, 0x72, 0x93, 0x49, 0xd6, 0x5a, 0x67, 0xc6, 0x6b, 0x4f, 0x52, 0xf2, 0x09,
	0x38, 0x73, 0xe3, 0x8e, 0x04, 0x5f, 0x80, 0x13, 0x87, 0xfd, 0x02, 0x5c, 0x39, 0xf0, 0x59, 0x38,
	0x21, 0xdb, 0x63, 0xc7, 0x76, 0x9c, 0xa4, 0x3d, 0xf4, 0x36, 0xf3, 0xbc, 0xfc, 0x9e, 0x17, 0x3f,
	0x2f, 0x63, 0xd8, 0xec, 0x0c, 0x74, 0xc5, 0xb4, 0x18, 0x67, 0x78, 0xcd, 0x39, 0x8e, 0x3e, 0x92,
	0x0a, 0x7d, 0xc6, 0xfa, 0x06, 0x39, 0x71, 0xa9, 0xd7, 0xc3, 0xde, 0x49, 0x97, 0xd8, 0x1d, 0x4b,
	0x37, 0x39, 0xb3, 0x3c, 0x49, 0xe9, 0x30, 0x2e, 0x71, 0x63, 0x69, 0xa6, 0x49, 0x2c, 0xdb, 0xe3,
	0xcb, 0x7f, 0x23, 0xc8, 0x55, 0x2c, 0xa2, 0x71, 0xf2, 0x42, 0xeb, 0xbc, 0xd4, 0x29, 0x51, 0xc9,
	0xeb, 0x21, 0xb1, 0x39, 0xc6, 0xb0, 0xd2, 0xd0, 0x06, 0x24, 0x8f, 0x0a, 0xa8, 0xb8, 0xa9, 0xba,
	0x67, 0x2c, 0x43, 0xfa, 0xc2, 0x62, 0x23, 0xbd, 0x4b, 0xac, 0x96, 0x49, 0x3a, 0xf9, 0xa5, 0x02,
	0x2a, 0xa6, 0xd5, 0x08, 0x0d, 0x3f, 0x83, 0xf5, 0x16, 0xe9, 0x58, 0x84, 0xdb, 0xf9, 0xe5, 0xc2,
	0x72, 0x71, 0xab, 0xf4, 0x48, 0xf1, 0x9c, 0x55, 0x92, 0xcc, 0x28, 0x42, 0xb6, 0x4a, 0xb9, 0x35,
	0x2e, 0x2f, 0xff, 0x52, 0x46, 0xaa, 0xaf, 0x2e, 0x9d, 0x42, 0x3a, 0xcc, 0xc5, 0x59, 0x58, 0x7e,
	0x45, 0xc6, 0xc2, 0x21, 0xe7, 0x88, 0x73, 0xb0, 0x3a, 0xd2, 0x8c, 0x21, 0x11, 0x8e, 0x78, 0x97,
	0xd3, 0xa5, 0x4f, 0x91, 0xfc, 0x0d, 0xec, 0xc4, 0xcc, 0xd9, 0x26, 0xa3, 0x36, 0xc1, 0xfb, 0xb0,
	0x29, 0x48, 0xf5, 0x33, 0x01, 0x35, 0x21, 0x60, 0x09, 0x36, 0x1a, 0xac, 0x4b, 0xdc, 0xc0, 0x97,
	0x5c, 0x66, 0x70, 0x97, 0xff, 0x44, 0x90, 0x3b, 0x23, 0x06, 0x99, 0xca, 0xd4, 0x7c, 0xc8, 0x50,
	0x3e, 0x96, 0xa2, 0xf9, 0x48, 0x02, 0xbb, 0xaf, 0x7c, 0x3c, 0x80, 0x9d, 0x98, 0x39, 0x2f, 0x1f,
	0xf2, 0x1f, 0x08, 0xfe, 0x5f, 0x23, 0xfc, 0x4e, 0x21, 0x55, 0xe3, 0x21, 0xbd, 0xef, 0x87, 0x34,
	0x85, 0x74, 0x5f, 0xf1, 0xfc, 0x86, 0x00, 0x87, 0x8d, 0x89, 0xaf, 0xbb, 0x0b, 0x6b, 0xd5, 0x1f,
	0x75, 0x9b, 0xdb, 0x2e, 0xca, 0x86, 0x2a, 0x6e, 0xb8, 0x06, 0x19, 0x21, 0xda, 0xe2, 0x1a, 0x1f,
	0xda, 0x2e, 0xe0, 0x76, 0xe9, 0x61, 0x92, 0xdf, 0x1e, 0x94, 0xe2, 0x09, 0xaa, 0x51, 0x3d, 0xf9,
	0x04, 0xd6, 0xbc, 0x13, 0xde, 0x82, 0xf5, 0x6f, 0xe9, 0x2b, 0xca, 0x6e, 0x68, 0x36, 0xe5, 0x5c,
	0xd4, 0x21, 0xa5, 0x3a, 0xed, 0x67, 0x91, 0x73, 0x69, 0x71, 0x66, 0x9a, 0xa4, 0x9b, 0x5d, 0x92,
	0xdf, 0x20, 0x78, 0xeb, 0x5c, 0xb7, 0x7d, 0x78, 0xdb, 0xcf, 0x70, 0xbc, 0x95, 0x50, 0x42, 0x2b,
	0xd5, 0xe2, 0x79, 0x2e, 0xfa, 0xfe, 0x26, 0x20, 0xde, 0x57, 0xa6, 0x7f, 0x47, 0x90, 0x8b, 0x9a,
	0x13, 0xb9, 0x6e, 0xc2, 0x96, 0xa0, 0x39, 0xec, 0x3c, 0x72, 0x3d, 0xfc, 0x30, 0xd9, 0x43, 0x91,
	0xd3, 0x90, 0xbc, 0xeb, 0x88, 0x1a, 0x46, 0x90, 0xbe, 0x84, 0x6c, 0x5c, 0x60, 0x91, 0xa7, 0x9b,
	0x61, 0x4f, 0xdf, 0x20, 0xd8, 0x6d, 0xbd, 0x1c, 0xf2, 0x33, 0x76, 0x43, 0xef, 0x54, 0xcf, 0x5f,
	0xc7, 0xf3, 0x7c, 0xec, 0x47, 0x91, 0x0c, 0x77, 0x5f, 0xa9, 0xde, 0x83, 0x07, 0x53, 0x06, 0x45,
	0x9b, 0xd6, 0xe1, 0x83, 0x1a, 0xe1, 0x4e, 0x5e, 0x9a, 0xbd, 0x36, 0x33, 0x86, 0x03, 0x52, 0x3f,
	0xb3, 0x9f, 0x32, 0xcb, 0xad, 0x6f, 0x9d, 0xf6, 0x2f, 0xda, 0x41, 0x65, 0x1d, 0x02, 0x5c, 0xb4,
	0x9d, 0xfa, 0x11, 0x9f, 0xc5, 0x31, 0x12, 0xa2, 0xc8, 0x0d, 0x28, 0x2e, 0x86, 0x12, 0xdf, 0x58,
	0x86, 0xb4, 0x2f, 0x12, 0xa0, 0x6d, 0xaa, 0x11, 0x9a, 0x2c, 0x43, 0xa1, 0xc2, 0x28, 0xb7, 0x98,
	0x61, 0x10, 0xab, 0x46, 0x78, 0x45, 0x33, 0xb5, 0x6b, 0xdd, 0xd0, 0xb9, 0x1e, 0xd4, 0xa6, 0xfc,
	0x2e, 0x3c, 0x9c, 0x23, 0x23, 0x62, 0xdc, 0x85, 0x5c, 0x8d, 0xf0, 0x0b, 0x63, 0xd8, 0xd7, 0x69,
	0x9d, 0xf6, 0x98, 0xaf, 0xfc, 0x0f, 0x82, 0x9d, 0x18, 0x43, 0xb8, 0x87, 0x61, 0x85, 0x86, 0x76,
	0x94, 0x73, 0xc6, 0x47, 0xb0, 0x3d, 0x22, 0xb4, 0xcb, 0xac, 0xab, 0x11, 0xb1, 0x6c, 0x9d, 0x51,
	0x51, 0x28, 0x19, 0x8f, 0xda, 0xf6, 0x88, 0xb8, 0x06, 0x1b, 0x03, 0x8d, 0xea, 0x3d, 0x62, 0x73,
	0xb1, 0xa7, 0x8e, 0x43, 0xc3, 0x60, 0xda, 0x96, 0xf2, 0x42, 0x48, 0x7b, 0x85, 0x1b, 0x28, 0x4b,
	0x9f, 0x3b, 0xa3, 0x25, 0xc4, 0xba, 0x53, 0xc9, 0x1e, 0xc2, 0x7e, 0x60, 0x2d, 0x29, 0x6f, 0x3f,
	0xc0, 0xc1, 0x0c, 0xbe, 0xc8, 0xc0, 0x13, 0x48, 0x77, 0x42, 0x74, 0xd1, 0x85, 0x79, 0x3f, 0x94,
	0x98, 0xe6, 0x58, 0x8d, 0x48, 0xcb, 0x7f, 0x21, 0xc8, 0xc6, 0x45, 0xf0, 0x13, 0x58, 0xb7, 0x89,
	0x35, 0xd2, 0x3b, 0x5e, 0x5e, 0xb7, 0x4a, 0x85, 0x59, 0x68, 0x4a, 0xcb, 0x93, 0x7b, 0x96, 0x52,
	0x7d, 0x15, 0xe9, 0xb5, 0xd3, 0x4b, 0xee, 0x11, 0x7f, 0x06, 0x2b, 0x7c, 0x6c, 0x7a, 0x28, 0xdb,
	0xa5, 0xa3, 0x45, 0x28, 0xca, 0xe5, 0xd8, 0x24, 0xaa, 0xab, 0x22, 0x1f, 0xc3, 0x8a, 0x73, 0x73,
	0x87, 0x6c, 0xe3, 0x79, 0xa3, 0xf9, 0x5d, 0x23, 0x9b, 0xc2, 0xbb, 0x80, 0x2b, 0xcd, 0xc6, 0xa5,
	0xda, 0x3c, 0x3f, 0xaf, 0xaa, 0x57, 0xad, 0xaa, 0xda, 0xae, 0x57, 0xaa, 0x59, 0x54, 0x5e, 0xf3,
	0xec, 0xc8, 0xdb, 0xee, 0x48, 0xbd, 0xf6, 0xbb, 0x54, 0xfe, 0x0a, 0x32, 0xe2, 0x2e, 0x92, 0xf5,
	0x18, 0x56, 0x2d, 0xa2, 0x75, 0xc7, 0x22, 0x2e, 0x49, 0xf1, 0xde, 0x46, 0x8a, 0xff, 0x36, 0x52,
	0xca, 0x8c, 0x19, 0x6d, 0xe7, 0xe3, 0xa8, 0x9e, 0x60, 0xe9, 0xe7, 0x55, 0x58, 0x17, 0xad, 0x88,
	0x1b, 0x90, 0x89, 0x3c, 0x29, 0xf0, 0xfe, 0xbc, 0x87, 0x8d, 0x74, 0x30, 0x83, 0x2b, 0x8a, 0x3d,
	0xe5, 0xe0, 0x45, 0x56, 0xf2, 0x04, 0x2f, 0xe9, 0x61, 0x30, 0xc1, 0x4b, 0xde, 0xe3, 0x29, 0x5c,
	0x05, 0x98, 0xac, 0x31, 0xbc, 0x37, 0x73, 0x25, 0x4b, 0xd2, 0xec, 0xad, 0x27, 0xa7, 0xf0, 0x73,
	0x48, 0x87, 0x67, 0x37, 0x7e, 0x7b, 0xce, 0xce, 0x91, 0xf6, 0xe7, 0x8d, 0x7b, 0x39, 0x85, 0x2f,
	0xe1, 0x7f, 0xb1, 0x89, 0x86, 0x0f, 0xe7, 0xcf, 0x56, 0xe9, 0x9d, 0x99, 0xfc, 0x00, 0xf5, 0x27,
	0x04, 0x85, 0x45, 0x23, 0x0c, 0x9f, 0x84, 0xa2, 0xbc, 0xcd, 0xdc, 0x94, 0x1e, 0xdf, 0x5e, 0x21,
	0xf0, 0xc4, 0x82, 0xbd, 0x99, 0x73, 0x0d, 0x07, 0xdb, 0x7a, 0xd1, 0x78, 0x94, 0x1e, 0xdd, 0x42,
	0xd2, 0xb7, 0x59, 0xfa, 0x17, 0xc1, 0x46, 0xbd, 0x4b, 0x28, 0x77, 0x9a, 0xb5, 0x01, 0x99, 0xc8,
	0xb8, 0x9a, 0x14, 0x51, 0xd2, 0x28, 0x9d, 0x14, 0x51, 0xe2, 0x8c, 0x93, 0x53, 0xb8, 0x17, 0x1a,
	0xb5, 0x91, 0x60, 0xde, 0x9b, 0xd2, 0x4c, 0x0a, 0xe4, 0x68, 0x81, 0x54, 0x60, 0xe7, 0x13, 0x58,
	0x75, 0x7b, 0x13, 0xe7, 0x82, 0xb1, 0x10, 0x6a, 0x5d, 0x69, 0x27, 0x46, 0xf5, 0xf5, 0x4e, 0xbf,
	0x00, 0xe8, 0x0c, 0xf4, 0x2b, 0xdb, 0x5d, 0xb1, 0xf8, 0x60, 0xaa, 0x83, 0x9f, 0xea, 0xc4, 0xe8,
	0x36, 0x4d, 0xae, 0x33, 0x6a, 0xe7, 0x7f, 0xdd, 0x70, 0x1f, 0x81, 0xce, 0x7f, 0x93, 0xb7, 0x93,
	0xcb, 0xab, 0xdf, 0x2f, 0x77, 0x06, 0xfa, 0xf5, 0x9a, 0x2b, 0xff, 0xf1, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x92, 0x84, 0x78, 0x95, 0x52, 0x0d, 0x00, 0x00,
}
